security:
  oauth2:
    client:
      client-id: ENC(qZwt/FNjcHbbPI9qKFNPqw==) # oa
      client-secret: ENC(3Ih+nwx0eqElycFAyO2TvA==) # oa
      scope: server

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://qlp-mysql:3306/qlp?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /book/save
    - /bookType/list/*
    - /bookType/save
    - /attr/list
    - /attr/list/*