## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(lAV470xq0K42Nl2EBowj9w==) #gen
      client-secret: ENC(V+MvP5UFO8WmqCybQtNNjQ==)
      scope: server

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://qlp-mysql:3306/qlp?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  resources:
    static-locations: classpath:/static/,classpath:/views/

# 直接放行URL
ignore:
  urls:
  - /actuator/**
